spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: BookQueryService
          uri: http://localhost:8085/
          predicates:
            - Path=/bookquery/**
        - id: BookCommand
          uri: http://localhost:8082/
          predicates:
            - Path=/bookcommand/**
        - id: BorrowingService
          uri: http://localhost:8084/
          predicates:
            - Path=/borrowing/**
        - id: CustomerService
          uri: http://localhost:8070/
          predicates:
            - Path=/customer/**
        - id: ReviewService
          uri: http://localhost:8083/
          predicates:
            - Path=/review/**

server:
  port: 8000
